# Generated by Django 4.2.23 on 2025-08-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(default='Hakkımızda', max_length=200, verbose_name='Başlık')),
                ('kisa_aciklama', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('uzun_aciklama', models.TextField(blank=True, verbose_name='Uzun Açıklama')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Görsel (opsiyonel)')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Ana sayfada göster')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda Bölümleri',
                'ordering': ['order', '-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='Haber',
        ),
    ]
