# Generated by Django 4.2.23 on 2025-08-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_about_delete_haber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(default='Projelerimiz', max_length=200, verbose_name='Başlık')),
                ('kisa_aciklama', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='showcase/', verbose_name='Görsel (sağ taraf)')),
                ('buton_yazi', models.CharField(default='Projeleri Gör', max_length=50, verbose_name='Buton Yazısı')),
                ('buton_link', models.CharField(default='/projeler', max_length=255, verbose_name='Buton Linki')),
                ('arkaplan', models.CharField(default='#f6f6f6', max_length=30, verbose_name='Arka plan rengi (hex veya css)')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Ana sayfada göster')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Showcase',
                'verbose_name_plural': 'Showcase Bölümleri',
                'ordering': ['order', '-updated_at'],
            },
        ),
    ]
