# Generated by Django 4.2.23 on 2025-08-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_showcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriGorsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='galeri/')),
                ('alt_baslik', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
