# Generated by Django 4.2.23 on 2025-08-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0004_galerigorsel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Istatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Başlık')),
                ('sayi', models.PositiveIntegerField(verbose_name='Sayı')),
                ('ikon', models.ImageField(blank=True, null=True, upload_to='istatistik_ikon', verbose_name='İkon (opsiyonel)')),
                ('siralama', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'İstatistik',
                'verbose_name_plural': 'İstatistikler',
                'ordering': ['siralama'],
            },
        ),
    ]
