# Generated by Django 4.2.23 on 2025-08-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0005_istatistik'),
    ]

    operations = [
        migrations.CreateModel(
            name='IstatistikArkaplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=100, verbose_name='Arkaplan Başlığı')),
                ('resim', models.ImageField(upload_to='istatistik_arkaplan/', verbose_name='Arkaplan Resmi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
            ],
            options={
                'verbose_name': 'İstatistik Arkaplan',
                'verbose_name_plural': 'İstatistik Arkaplanlar',
            },
        ),
        migrations.RemoveField(
            model_name='istatistik',
            name='ikon',
        ),
        migrations.AlterField(
            model_name='istatistik',
            name='sayi',
            field=models.PositiveIntegerField(verbose_name='Sayısal Değer'),
        ),
    ]
