# Generated by Django 4.2.23 on 2025-08-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0006_istatistikarkaplan_remove_istatistik_ikon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('kisa_aciklama', models.TextField(max_length=300, verbose_name='Kısa Açıklama')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('kapak_resmi', models.ImageField(upload_to='blog/', verbose_name='Kapak Resmi')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='SEO URL')),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('meta_aciklama', models.CharField(blank=True, max_length=300, verbose_name='Meta Açıklama')),
                ('meta_etiketler', models.CharField(blank=True, max_length=200, verbose_name='Meta Etiketler')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-yayin_tarihi'],
            },
        ),
    ]
