# Generated by Django 4.2.23 on 2025-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0007_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(default='Spider Metal', max_length=200, verbose_name='Footer Başlığı')),
                ('adres', models.TextField(default='A. 1649 Sk. No: 61 Turan Mah. Bayraklı - İzmir, Türkiye, 35540', verbose_name='Adres')),
                ('telefon', models.CharField(default='+90 (232) 366 98 98', max_length=20, verbose_name='Telefon')),
                ('whatsapp', models.CharField(default='+90 (532) 296 90 00', max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(default='info@spidermetal.com', max_length=254, verbose_name='E-posta')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('telif_hakki', models.CharField(default='© 2025 Spider Metal. Tüm hakları saklıdır.', max_length=255, verbose_name='Telif Hakkı Metni')),
            ],
            options={
                'verbose_name': 'Footer Ayarı',
                'verbose_name_plural': 'Footer Ayarları',
            },
        ),
    ]
