# Generated by Django 4.2.23 on 2025-08-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0009_iletisimmesaji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='baslik_en',
            field=models.CharField(default='Hakkımızda', max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='about',
            name='baslik_ru',
            field=models.CharField(default='Hakkımızda', max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='about',
            name='baslik_tr',
            field=models.CharField(default='Hakkımızda', max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='about',
            name='kisa_aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='about',
            name='kisa_aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='about',
            name='kisa_aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='about',
            name='uzun_aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='Uzun Açıklama'),
        ),
        migrations.AddField(
            model_name='about',
            name='uzun_aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Uzun Açıklama'),
        ),
        migrations.AddField(
            model_name='about',
            name='uzun_aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Uzun Açıklama'),
        ),
        migrations.AddField(
            model_name='footerayarlari',
            name='adres_en',
            field=models.TextField(default='A. 1649 Sk. No: 61 Turan Mah. Bayraklı - İzmir, Türkiye, 35540', null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='footerayarlari',
            name='adres_ru',
            field=models.TextField(default='A. 1649 Sk. No: 61 Turan Mah. Bayraklı - İzmir, Türkiye, 35540', null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='footerayarlari',
            name='adres_tr',
            field=models.TextField(default='A. 1649 Sk. No: 61 Turan Mah. Bayraklı - İzmir, Türkiye, 35540', null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='footerayarlari',
            name='baslik_en',
            field=models.CharField(default='Spider Metal', max_length=200, null=True, verbose_name='Footer Başlığı'),
        ),
        migrations.AddField(
            model_name='footerayarlari',
            name='baslik_ru',
            field=models.CharField(default='Spider Metal', max_length=200, null=True, verbose_name='Footer Başlığı'),
        ),
        migrations.AddField(
            model_name='footerayarlari',
            name='baslik_tr',
            field=models.CharField(default='Spider Metal', max_length=200, null=True, verbose_name='Footer Başlığı'),
        ),
        migrations.AddField(
            model_name='footerayarlari',
            name='telif_hakki_en',
            field=models.CharField(default='© 2025 Spider Metal. Tüm hakları saklıdır.', max_length=255, null=True, verbose_name='Telif Hakkı Metni'),
        ),
        migrations.AddField(
            model_name='footerayarlari',
            name='telif_hakki_ru',
            field=models.CharField(default='© 2025 Spider Metal. Tüm hakları saklıdır.', max_length=255, null=True, verbose_name='Telif Hakkı Metni'),
        ),
        migrations.AddField(
            model_name='footerayarlari',
            name='telif_hakki_tr',
            field=models.CharField(default='© 2025 Spider Metal. Tüm hakları saklıdır.', max_length=255, null=True, verbose_name='Telif Hakkı Metni'),
        ),
        migrations.AddField(
            model_name='galerigorsel',
            name='alt_baslik_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galerigorsel',
            name='alt_baslik_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galerigorsel',
            name='alt_baslik_tr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='istatistik',
            name='baslik_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='istatistik',
            name='baslik_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='istatistik',
            name='baslik_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='istatistikarkaplan',
            name='baslik_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arkaplan Başlığı'),
        ),
        migrations.AddField(
            model_name='istatistikarkaplan',
            name='baslik_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arkaplan Başlığı'),
        ),
        migrations.AddField(
            model_name='istatistikarkaplan',
            name='baslik_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arkaplan Başlığı'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='baslik_en',
            field=models.CharField(default='Projelerimiz', max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='baslik_ru',
            field=models.CharField(default='Projelerimiz', max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='baslik_tr',
            field=models.CharField(default='Projelerimiz', max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='buton_yazi_en',
            field=models.CharField(default='Projeleri Gör', max_length=50, null=True, verbose_name='Buton Yazısı'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='buton_yazi_ru',
            field=models.CharField(default='Projeleri Gör', max_length=50, null=True, verbose_name='Buton Yazısı'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='buton_yazi_tr',
            field=models.CharField(default='Projeleri Gör', max_length=50, null=True, verbose_name='Buton Yazısı'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='kisa_aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='kisa_aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='kisa_aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='slider',
            name='aciklama_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='aciklama_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='aciklama_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='baslik_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='baslik_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='baslik_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
