# Generated by Django 4.2.23 on 2025-08-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0010_product_about_baslik_en_about_baslik_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='baslik_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='blog',
            name='baslik_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='blog',
            name='baslik_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='blog',
            name='icerik_en',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='blog',
            name='icerik_ru',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='blog',
            name='icerik_tr',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='blog',
            name='kisa_aciklama_en',
            field=models.TextField(max_length=300, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='blog',
            name='kisa_aciklama_ru',
            field=models.TextField(max_length=300, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='blog',
            name='kisa_aciklama_tr',
            field=models.TextField(max_length=300, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_aciklama_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_aciklama_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_aciklama_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_etiketler_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Etiketler'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_etiketler_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Etiketler'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_etiketler_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Etiketler'),
        ),
        migrations.AddField(
            model_name='iletisimmesaji',
            name='mesaj_en',
            field=models.TextField(null=True, verbose_name='Mesaj'),
        ),
        migrations.AddField(
            model_name='iletisimmesaji',
            name='mesaj_ru',
            field=models.TextField(null=True, verbose_name='Mesaj'),
        ),
        migrations.AddField(
            model_name='iletisimmesaji',
            name='mesaj_tr',
            field=models.TextField(null=True, verbose_name='Mesaj'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
